services:
  postgres:
    image: pgvector/pgvector:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app_pg

  redis:
    image: redis
    ports:
      - 6379:6379