import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import UserContextProvider from "../context/userContext";
import FormsContextProvider from "../context/formsContext";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hirable",
  description: "Generated by Ujjwal",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <FormsContextProvider>
          <UserContextProvider>{children}</UserContextProvider>
        </FormsContextProvider>

        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </body>
    </html>
  );
}
